vlib $env(SOC_IT_SIMULATION_PATH)/cnn_layer_accel
vmap cnn_layer_accel $env(SOC_IT_SIMULATION_PATH)/cnn_layer_accel
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router/tile_router_v1_00_a_input_port.v
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router/tile_router_v1_00_a_output_arbiter.v
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router/tile_router_v1_00_a_output_port.v
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router/pe_interface.v
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router/tile_router_v1_00_a.v
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/ingress_interface.v
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/layer_engine_docker.sv
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router_network.v
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/ingress_interface_packetizer.v"
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/msg_intf.v"
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/ingress_interface_cache.v"
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_layer_engine_controller.v
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_layer_engine_pe.v
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/master_if_arbiter_nway.v
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/master_transactor.v
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel.v
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_defines.vh
vlog -lint -sv +define+simulation +define+SIMULATION -work cnn_layer_accel +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker/tile_router +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/layer_engine_docker +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_layer_engine.v

