function    
[ ...
    li_inMaps, ...
    li_krnl3x3, ...
    li_krnl3x3bias, ...
    li_partMaps, ...
    li_resMaps ...
] = createLayerParams( ...
    inMaps, ...
    kernels3x3, ...
    bias3x3, ...
    resMaps, ...
    num_krnl_iter, ...
    krnl_iter, ...
    num_depth_iter, ...
    dpth_iter, ...
    depthBgn, ...
    depth, ...
    krnl3x3Bgn, ...
    numKrnl3x3, ...
    nOutRows, ...
    nOutCols, ...
    do_krnl1x1, ...
    do_resLayer, ...
    prevOutMaps ...
)
    li_inMaps = inMaps(:, :, depthBgn:(depthBgn + (depth - 1));
    li_krnl3x3 = kernels3x3(:, :, depthBgn:(depthBgn + (depth - 1)), krnl3x3Bgn:(krnl3x3Bgn + (numKrnl3x3 - 1)));
    li_krnl3x3bias = bias3x3(krnl3x3Bgn:(krnl3x3Bgn + (numKrnl3x3 - 1)));
    li_outMaps = zeros(nOutRows, nOutCols, numKrnl3x3);
    if(dpth_iter == 1)
        li_partMaps = [];
    else
        li_partMaps = prevOutMaps;
    end
    if(dpth_iter == 1 && do_resLayer)
        li_resMaps = resMaps(:, :, krnl3x3Bgn:(krnl3x3Bgn + (numKrnl3x3 - 1)));
    end
end

