function
[ ...
    li_outMaps
] = Process( ...
    li_inMaps, ...
    li_krnl3x3, ...
    li_krnl3x3bias, ...
    kernels1x1, ...
    bias1x1, ...
    li_partMaps, ...
    li_resMaps, ...
    num_krnl_iter, ...
    krnl_iter, ...
    num_depth_iter, ...
    dpth_iter, ...
    numKrnl3x3, ...
    nOutRows, ...
    nOutCols, ...
    do_krnl1x1, ...
    do_resLayer
)
    li_outMaps = zeros(nOutRows, nOutCols, numKrnl3x3);
    li_outMaps = Convolution(li_krnl3x3, li_inMaps, li_outMaps, li_krnl3x3bias);  

end