######################################################################
#
# File name : sim_tb_top_simulate.do
# Created on: Wed Feb 19 15:20:59 EST 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib sim_tb_top_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {sim_tb_top_wave.do}

view wave
view structure
view signals

do {sim_tb_top.udo}

run 1000ns