######################################################################
#
# File name : sim_tb_top_wave.do
# Created on: Wed Feb 19 15:20:59 EST 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
