# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcvu37p-fsvh2892-2-e/krnl1x1_bram/krnl1x1_bram.xci
# IP: The module: 'krnl1x1_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcvu37p-fsvh2892-2-e/krnl1x1_bram/krnl1x1_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'krnl1x1_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcvu37p-fsvh2892-2-e/krnl1x1_bram/krnl1x1_bram.xci
# IP: The module: 'krnl1x1_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcvu37p-fsvh2892-2-e/krnl1x1_bram/krnl1x1_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'krnl1x1_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
