# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip_viv2019.1/xcvu37p-fsvh2892-2-e/clk_wiz/clk_wiz.xci
# IP: The module: 'clk_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip_viv2019.1/xcvu37p-fsvh2892-2-e/clk_wiz/clk_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip_viv2019.1/xcvu37p-fsvh2892-2-e/clk_wiz/clk_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip_viv2019.1/xcvu37p-fsvh2892-2-e/clk_wiz/clk_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip_viv2019.1/xcvu37p-fsvh2892-2-e/clk_wiz/clk_wiz.xci
# IP: The module: 'clk_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip_viv2019.1/xcvu37p-fsvh2892-2-e/clk_wiz/clk_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip_viv2019.1/xcvu37p-fsvh2892-2-e/clk_wiz/clk_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip_viv2019.1/xcvu37p-fsvh2892-2-e/clk_wiz/clk_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
