file delete -force -- ./work


vlib work


# Xilinx Lib
vlog -lint -sv -work work $env(GLBL_PATH)/glbl.v


# Verification Files
vlog -lint -sv +define+SIMULATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ +incdir+$env(SOC_IT_ROOT)/verif_lib/ $env(SOC_IT_ROOT)/cnn_layer_accel/verification/clock_gen.v
vlog -lint -sv +define+SIMULATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ +incdir+$env(SOC_IT_ROOT)/verif_lib/ $env(SOC_IT_ROOT)/cnn_layer_accel/verification/cnn_layer_accel_quad_intf.sv
vlog -lint -sv +define+SIMULATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ +incdir+$env(SOC_IT_ROOT)/verif_lib/ $env(SOC_IT_ROOT)/cnn_layer_accel/verification/cnn_layer_accel_synch_intf.sv
vlog -lint -sv +define+SIMULATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ +incdir+$env(SOC_IT_ROOT)/verif_lib/ $env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/cnl_sc1_testbench.sv
vlog -lint -sv +define+SIMULATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ +incdir+$env(SOC_IT_ROOT)/verif_lib/ $env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/cnl_sc1_environment.sv
vlog -lint -sv +define+SIMULATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ +incdir+$env(SOC_IT_ROOT)/verif_lib/ $env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/cnl_sc1_generator.sv
vlog -lint -sv +define+SIMULATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ +incdir+$env(SOC_IT_ROOT)/verif_lib/ $env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/cnl_sc1_monitor.sv
vlog -lint -sv +define+SIMULATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ +incdir+$env(SOC_IT_ROOT)/verif_lib/ $env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/cnl_sc1_scoreboard.sv
vlog -lint -sv +define+SIMULATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ +incdir+$env(SOC_IT_ROOT)/verif_lib/ $env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/cnl_sc1_agent.sv
vlog -lint -sv +define+SIMULATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ +incdir+$env(SOC_IT_ROOT)/verif_lib/ $env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/cnl_sc1_driver.sv
vlog -lint -sv +define+SIMULATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/ +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ +incdir+$env(SOC_IT_ROOT)/verif_lib/ $env(SOC_IT_ROOT)/cnn_layer_accel/verification/scenario1/cnl_sc1_DUTOutput.sv


# Accel
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_awe_rowbuffers.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_prefetch_buffer.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/xilinx_simple_dual_port_no_change_ram.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/xilinx_true_dual_port_no_change_ram.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/xilinx_simple_dual_port_no_change_2_clock_ram.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_quad_bram_ctrl.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_quad.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/SRL_bit.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/SRL_bus.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_weight_table_top.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_weight_sequence_table0.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_weight_sequence_table1.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_awe_dsps.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_ce_dsps.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_ce_macc_0.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/cnn_layer_accel_ce_macc_1.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/awe_dsp_input_mux.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/signal_ext.v


# Xilinx IP
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/ip/xcku115/pixel_sequence_data_bram/simulation/blk_mem_gen_v8_3.v
vlog -lint -sv +define+SIMULATION +define+VERIFICATION -work work +incdir+$env(SOC_IT_ROOT)/soc_it_common/hardware/include +incdir+$env(SOC_IT_ROOT)/cnn_layer_accel/hardware/verilog/ $env(SOC_IT_ROOT)/cnn_layer_accel/hardware/ip/xcku115/pixel_sequence_data_bram/sim/pixel_sequence_data_bram.v
