onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/CE_CYCLE_COUNTER_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_ACTV_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_A_INPUT_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_B_INPUT_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_CE_CYCLE_CNT_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_CLG2_MAX_BRAM_3x3_KERNELS}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_CLG2_ROW_BUF_BRAM_DEPTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_C_INPUT_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_DATAIN_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_INPUT_MUX_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_KERNAL_SIZE_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_MODE_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_PACKET_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_PFB_DOUT_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_PIXEL_DATAIN_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_PIXEL_DATAOUT_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_PIXEL_DOUT_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_P_INPUT_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_P_OUTPUT_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_RELU_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_WEIGHTIN_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_WEIGHT_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_WHT_DOUT_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/C_WHT_TBL_ADDR_WIDTH}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ST_AWE_CE_ACTIVE}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ST_AWE_CE_PRIM_BUFFER}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ST_IDLE}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ST_SEND_COMPLETE}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ST_WAIT_JOB_DONE}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ST_WAIT_PFB_LOAD}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/actv_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/actv_out}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/all_pfb_loaded}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/all_pip_primed}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/awe_carryout}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/awe_cascade_carryout}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/awe_cascade_dataout}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/awe_cascade_dataout_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/awe_dataout}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/awe_dataout_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/awe_last_kernel}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/cascade_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/cascade_in_data}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/cascade_in_ready}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/cascade_in_ready_arr}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/cascade_in_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/cascade_out_data}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/cascade_out_ready}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/cascade_out_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ce0_pixel_datain}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ce0_pixel_dataout}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ce0_pixel_dataout_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ce1_pixel_datain}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ce1_pixel_dataout}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ce1_pixel_dataout_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ce_cycle_counter}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ce_execute}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ce_wht_table_dout}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ce_wht_table_dout_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/clk_core}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/clk_if}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/cncl_fetch_req}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/config_accept}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/config_data}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/config_data_arr}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/config_mode}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/config_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/conv_out_fmt_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/crpd_input_col_end_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/crpd_input_col_start_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/crpd_input_row_end_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/crpd_input_row_start_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ctrl_last_kernel}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ctrl_pix_seq_bram_rdAddr}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/ctrl_pix_seq_bram_rden}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/cycle_counter}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/dsp_kernel_size_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/gray_code}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/idx}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/idx0}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/idx1}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/idx2}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/idx3}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/idx4}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/input_col}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/input_row}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_accept}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_accept_r}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_accept_w}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_complete}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_complete_ack}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_fetch_ack}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_fetch_ack_r}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_fetch_ack_w}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_fetch_complete}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_fetch_complete_r}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_fetch_complete_w}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_fetch_in_progress}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_fetch_request}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_fetch_request_w}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_parameters}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_parameters_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/job_start}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/kernel_config_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/last_kernel}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/master_quad_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/move_one_row_down}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/next_kernel}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/next_row}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/next_state_tran}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/num_expd_input_cols_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/num_expd_input_rows_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/num_kernels_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/num_output_cols_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/num_output_rows_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/output_col}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/output_depth}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/output_row}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/padding_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pfb_datain}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pfb_dataout}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pfb_full_count_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pfb_loaded}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pfb_rden}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pfb_wren}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pip_primed}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pipeline_flushed}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pix_seq_bram_dout}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pix_seq_bram_rdAddr}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pix_seq_bram_rden}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pix_seq_bram_wrAddr}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pix_seq_bram_wren}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pix_seq_data_full_count_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pixel_data}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pixel_data_arr}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pixel_data_r}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pixel_ready}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/pixel_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/result_accept}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/result_data}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/result_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/row_matric_wrAddr}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/rst}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/slv_dbg_data}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/slv_dbg_rdAck}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/slv_dbg_rdAddr}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/slv_dbg_rdAddr_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/slv_dbg_rdAddr_w}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/slv_dwc_idx}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/slv_pix_seq_bram_rden}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/slv_wht_table_rden}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/slv_wht_table_sel}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/slv_wht_tble_rdAddr}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/state}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/state_s}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/stride_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/upsample_cfg}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/weight_data}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/weight_data_arr}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/weight_ready}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/weight_valid}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/wht_config_wren}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/wht_seq_addr0}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/wht_seq_addr1}
add wave -noupdate {/cnl_sc1_testbench/QUAD[0]/i0_cnn_layer_accel_quad/wht_sequence_selector}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {12556 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 193
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {12502 ns} {12590 ns}
