# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mdl/izo5011/SOC_IT/cnn_layer_accel/hardware/ip/xcku115/xilinx_async_fwft_fifo_count/xilinx_async_fwft_fifo_count.xci
# IP: The module: 'xilinx_async_fwft_fifo_count' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/SOC_IT/cnn_layer_accel/hardware/ip/xcku115/xilinx_async_fwft_fifo_count/xilinx_async_fwft_fifo_count/xilinx_async_fwft_fifo_count_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_async_fwft_fifo_count'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/mdl/izo5011/SOC_IT/cnn_layer_accel/hardware/ip/xcku115/xilinx_async_fwft_fifo_count/xilinx_async_fwft_fifo_count/xilinx_async_fwft_fifo_count.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_async_fwft_fifo_count'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/mdl/izo5011/SOC_IT/cnn_layer_accel/hardware/ip/xcku115/xilinx_async_fwft_fifo_count/xilinx_async_fwft_fifo_count_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_async_fwft_fifo_count'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/mdl/izo5011/SOC_IT/cnn_layer_accel/hardware/ip/xcku115/xilinx_async_fwft_fifo_count/xilinx_async_fwft_fifo_count.xci
# IP: The module: 'xilinx_async_fwft_fifo_count' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/SOC_IT/cnn_layer_accel/hardware/ip/xcku115/xilinx_async_fwft_fifo_count/xilinx_async_fwft_fifo_count/xilinx_async_fwft_fifo_count_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_async_fwft_fifo_count'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/mdl/izo5011/SOC_IT/cnn_layer_accel/hardware/ip/xcku115/xilinx_async_fwft_fifo_count/xilinx_async_fwft_fifo_count/xilinx_async_fwft_fifo_count.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_async_fwft_fifo_count'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/mdl/izo5011/SOC_IT/cnn_layer_accel/hardware/ip/xcku115/xilinx_async_fwft_fifo_count/xilinx_async_fwft_fifo_count_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_async_fwft_fifo_count'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
