# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcku115/prefetch_buffer_fifo/prefetch_buffer_fifo.xci
# IP: The module: 'prefetch_buffer_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcku115/prefetch_buffer_fifo/prefetch_buffer_fifo/prefetch_buffer_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'prefetch_buffer_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcku115/prefetch_buffer_fifo/prefetch_buffer_fifo/prefetch_buffer_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'prefetch_buffer_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcku115/prefetch_buffer_fifo/prefetch_buffer_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prefetch_buffer_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcku115/prefetch_buffer_fifo/prefetch_buffer_fifo.xci
# IP: The module: 'prefetch_buffer_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcku115/prefetch_buffer_fifo/prefetch_buffer_fifo/prefetch_buffer_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'prefetch_buffer_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcku115/prefetch_buffer_fifo/prefetch_buffer_fifo/prefetch_buffer_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'prefetch_buffer_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcku115/prefetch_buffer_fifo/prefetch_buffer_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prefetch_buffer_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
