# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcvu37p-fsvh2892-2-e/trans_in_fifo/trans_in_fifo.xci
# IP: The module: 'trans_in_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcvu37p-fsvh2892-2-e/trans_in_fifo/trans_in_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'trans_in_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcvu37p-fsvh2892-2-e/trans_in_fifo/trans_in_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'trans_in_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcvu37p-fsvh2892-2-e/trans_in_fifo/trans_in_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trans_in_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcvu37p-fsvh2892-2-e/trans_in_fifo/trans_in_fifo.xci
# IP: The module: 'trans_in_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcvu37p-fsvh2892-2-e/trans_in_fifo/trans_in_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'trans_in_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcvu37p-fsvh2892-2-e/trans_in_fifo/trans_in_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'trans_in_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mdl/izo5011/IkennaWorkSpace/cnn_layer_accel/hardware/ip/xcvu37p-fsvh2892-2-e/trans_in_fifo/trans_in_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'trans_in_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
