# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mdl/izo5011/SOC_IT/cnn_layer_accel/hardware/ip/xcku115/xilinx_dual_port_2_clock_ram/xilinx_dual_port_2_clock_ram.xci
# IP: The module: 'xilinx_dual_port_2_clock_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/SOC_IT/cnn_layer_accel/hardware/ip/xcku115/xilinx_dual_port_2_clock_ram/xilinx_dual_port_2_clock_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_dual_port_2_clock_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/mdl/izo5011/SOC_IT/cnn_layer_accel/hardware/ip/xcku115/xilinx_dual_port_2_clock_ram/xilinx_dual_port_2_clock_ram.xci
# IP: The module: 'xilinx_dual_port_2_clock_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/SOC_IT/cnn_layer_accel/hardware/ip/xcku115/xilinx_dual_port_2_clock_ram/xilinx_dual_port_2_clock_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_dual_port_2_clock_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
